In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

digits = load_digits()

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train , y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [19]:
lr= LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9629629629629629

In [21]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [30]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

In [32]:
from sklearn.model_selection import KFold
kf =KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [34]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [36]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [44]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)

In [66]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]

    scores_lr.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))  
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))                 
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50),X_train,X_test,y_train,y_test))                  

In [67]:
scores_rf

[0.9298831385642737, 0.9532554257095158, 0.9248747913188647]

In [68]:
scores_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [70]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [76]:
#for coding
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [77]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [86]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.925     , 0.9       , 0.94986072, 0.96100279, 0.90529248])